### ISSUE TITLE
Fix that, when writing a code consisting of more than one word, Open Ethnographer breaks it down into several one-word codes

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#109] opened 2017-11-14 12:30 UTC
For example: if you code something as `migration crisis` Open Ethno will create two codes, `migration` and `crisis`.

**Comment by tanius** [comment] 2017-11-14 20:54
Duplicate of #104.

**Closed by tanius** 2017-11-14 20:54 UTC
Labels: bug
