### ISSUE TITLE
API authentication no longer works with Admin API keys

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#245] opened 2020-07-13 14:07 UTC
this works in browser, when I am logged in:
```
https://edgeryders.eu/annotator/annotations.json?&api_key=my_api_key 
```

However, the same link entered in a private browsing window does not. 

Also:  

```
>>> import requests
>>> call = 'https://edgeryders.eu/annotator/annotations.json?api_key=my_api_key'
>>> response = requests.get(call)
>>> print (response)
<Response [404]>
```

**Comment by albertocottica** [comment] 2020-07-13 14:19
Already tried: generated a brand new API key, then tried the new one. No joy. 

Also tried generating a "all users" API key, in case the "single user" one need the username as a parameter.  Again, no joy. 

Finally: 

```
>>> call = call = 'https://edgeryders.eu/topics/private-messages/alberto.json?user_name=alberto&api_key=' + api_key
>>> response = requests.get(call)
>>> print(response)
<Response [403]>
```

It appears a case of unauthorized access.

**Comment by tanius** [comment] 2020-07-13 17:42
We had a similar issue with the [`multisite_account.json` API endpoint](https://edgeryders.eu/t/-/7904#heading--3-4) after the recent Discourse update. So this probably has the same underlying cause and needs the same code changes to fix it.

The same issue as reported here (Admin API key auth failing) also happens with at least the following other of our custom API endpoints:

```
https://edgeryders.eu/admin/consent.json?api_key=...
```

@damingo: when fixing this, please make sure that all [our custom API endpoints](https://edgeryders.eu/t/7904) work with authentication by Discourse Admin API key.

----

Side note:

> Also tried generating a "all users" API key, in case the "single user" one need the username as a parameter.

It's the other way around. The "all users" API key needs a username as a parameter, since it is the master API key that allows to impersonate all users. Which user is given by the additional `username` parameter. This makes it a "dangerous" API key and it should not be used for anything except strictly necessary.

**Comment by tanius** [comment] 2020-07-13 18:54
> We had a similar issue with the multisite_account.json API endpoint after the recent Discourse update. So this probably has the same underlying cause and needs the same code changes to fix it.

Actually, no. The issue seems rather that authentication with Admin API keys supplied as a GET parameter is no longer possible at all in Discourse. It was a deprecated feature before, and probably now they want everyone to supply the Admin API key in a HTTP custom header.

Because: any call to protected Discourse APIs with a valid Admin API call supplied as a GET parameter fails now, or is equivalent to not supplying any admin API key at all. For example, a call to `https://edgeryders.eu/u/{matthias}.json?api_key=...` leaves out listing the custom fields. Compare that to visiting `https://edgeryders.eu/u/{username}.json` in a logged-in browser window, where the custom fields will be listed due to cookie authentication.

So far, we exclusively supplied the Admin API keys by GET parameter because our proxy server setup (or something else) interfered with supplying them as a custom HTTP header. We'll have to fix our proxy server, then.

**Comment by tanius** [comment] 2020-07-14 00:59
Indeed Discourse changed how access to the API is being done, retiring the `api_key` GET parameter mechanism:

> ### Deprecation Warning!
> 
> On April 6th, 2020 we dropped support for all non-HTTP header based authentication (excluding some rss, mail-receiver, and ics routes). This means that API requests that have an api_key and api_username in the query params or in the HTTP body of the request will soon stop working. Please see the example cURL request below for how to update your API requests to use the HTTP headers for authentication.
> 
> ([source](https://meta.discourse.org/t/22706))

The good news is that the new mechanism using HTTP headers works without issues, also including with our custom API endpoints. Example command, to be used with your own Admin API key:

```
curl -X GET "https://edgeryders.eu/annotator/codes.json" -H "Api-Key: 11e3b3a......392214fe"
```

So basically, whether you send a GET or POST or PUT request, always add a HTTP header `Api-Key: ` with your API key.

Tentatively closing this issue as tests with `curl` as above were successful. Needs to be confirmed with all our custom API endpoints, still. Also we'll need to update our custom code in Discourse that accesses the Discourse API, but that's for another issue.

**Closed as completed** 2020-07-14 01:05 UTC
Labels: bug
