### ISSUE TITLE
Implement the OpenCare consent funnel and import consent data from Drupal

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/discourse#25] opened 2017-07-12 15:16 UTC
This time it would be site-wide. A rewording of the questions might be needed. Happy to help with those, even by editing the relevant HTML in the code.

**Comment by tanius** [comment] 2017-07-12 15:22
Duplicate of #22 :slightly_smiling_face:

**Closed by tanius** 2017-07-12 15:22 UTC
Labels: enhancement
